### PR TITLE
A11y-menu: Adding plugin to repo

### PR DESCRIPTION
**Pull request by efrigoli**

### CODE REVIEW

**Comment by efrigoli** [comment]
@jldust The initial commit of the megamenu plugin is ready for review! To test this, create a WordPress menu object, then add the Accessible Mega Menu block to a page or template and select your menu from the block settings pane. The ReadMe contains a roadmap for improvements to be made, but in its initial state, this creates an unstyled collapsible menu with an adjustable mobile breakpoint.

**Review by jldust — CHANGES_REQUESTED** [review]
@efrigoli There is a function in functions.php that is still leveraging an ACF function called `get_field()` which is causing a WOD. Removing lines 574-615 resolves the error. 

https://github.com/AtenDesignGroup/wordpress-starter/blob/407bd4270763cc6d081ce9bce33036b341da6b99/wp-content/themes/aten-fse/functions.php#L582

**Comment by efrigoli** [comment]
@jldust Code has been formatted using PHP Sniffer & Beautifier extension configured for WordPress coding standards. JS files have also been restructured to match the new WP custom block anatomy, and keyboard navigation is now functional again.

**Review by jldust — APPROVED** [review]
This is approved to merge, we will be addressing converting jQuery to basic JS and updating nested sub menus for keyboard support.

**Pull request merged**
